/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sisescola.view;

import br.com.sisescola.transferencia.Aluno;
import br.com.sisescola.dao.AlunoDAO;
import br.com.sisescola.accessories.ConexaoEscola;
import br.com.sisescola.transferencia.ModeloGrade;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import static javax.swing.JOptionPane.*;
import javax.swing.JTable;
import javax.swing.text.JTextComponent;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Vinicius
 */
public class APAluno extends javax.swing.JInternalFrame {

    private ConexaoEscola ce;
    private String sexo;
    private String responsavel;
    private String bolsista;
    private String alergico;
    private String doenca;
    private String turno;

    /**
     * Creates new form APAluno
     */
    public APAluno() throws Exception {
        ce = new ConexaoEscola();
        initComponents();
        popularTurma();
        bolsista = "NÃO";
        alergico = "NÃO";
        doenca = "NÃO";

        tbDados.addMouseListener(new APAluno.MouseHandler());

        tpAbas.setMnemonicAt(0, 'S');
        tpAbas.setMnemonicAt(1, 'M');

        atualizarGrade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgResponsavel = new javax.swing.ButtonGroup();
        bgBolsista = new javax.swing.ButtonGroup();
        bgAlergico = new javax.swing.ButtonGroup();
        bgSaude = new javax.swing.ButtonGroup();
        bgSexo = new javax.swing.ButtonGroup();
        bgTurno = new javax.swing.ButtonGroup();
        tpAbas = new javax.swing.JTabbedPane();
        spDados = new javax.swing.JScrollPane();
        tbDados = new javax.swing.JTable();
        pnManutencao = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ftCodigo = new javax.swing.JFormattedTextField(new Integer(0));
        tfNome = new javax.swing.JTextField();
        rbMasculino = new javax.swing.JRadioButton();
        rbFeminino = new javax.swing.JRadioButton();
        ftNascimento = new javax.swing.JFormattedTextField();
        tfNacionalidade = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tfPai = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfMae = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        rbPai = new javax.swing.JRadioButton();
        rbMae = new javax.swing.JRadioButton();
        rbOutro = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        ftCpf = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        tfOutro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        tfLogradouro = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        tfNumero = new javax.swing.JTextField();
        ftCelular = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        tfComplemento = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfBairro = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        ftCep = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        tfCidade = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        coUf = new javax.swing.JComboBox();
        jLabel20 = new javax.swing.JLabel();
        ftFone = new javax.swing.JFormattedTextField();
        jLabel21 = new javax.swing.JLabel();
        rbBolsistaSim = new javax.swing.JRadioButton();
        rbBolsistaNao = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        rbAlergicoSim = new javax.swing.JRadioButton();
        rbAlergicoNao = new javax.swing.JRadioButton();
        jLabel24 = new javax.swing.JLabel();
        tfAlergia = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        rbDoencaSim = new javax.swing.JRadioButton();
        rbDoencaNao = new javax.swing.JRadioButton();
        jLabel26 = new javax.swing.JLabel();
        tfDoenca = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        rbManha = new javax.swing.JRadioButton();
        rbTarde = new javax.swing.JRadioButton();
        rbNoite = new javax.swing.JRadioButton();
        rbIntegral = new javax.swing.JRadioButton();
        jLabel28 = new javax.swing.JLabel();
        coTurma = new javax.swing.JComboBox();
        jLabel29 = new javax.swing.JLabel();
        btSalvar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        bgResponsavel.add(rbPai);
        bgResponsavel.add(rbMae);
        bgResponsavel.add(rbOutro);

        bgBolsista.add(rbBolsistaSim);
        bgBolsista.add(rbBolsistaNao);

        bgAlergico.add(rbAlergicoSim);
        bgAlergico.add(rbAlergicoNao);
        rbAlergicoNao.setSelected(true);

        bgSaude.add(rbDoencaSim);
        bgSaude.add(rbDoencaNao);
        rbDoencaNao.setSelected(true);

        bgSexo.add(rbMasculino);
        bgSexo.add(rbFeminino);

        bgTurno.add(rbManha);
        bgTurno.add(rbTarde);
        bgTurno.add(rbNoite);
        bgTurno.add(rbIntegral);

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cadastro de Alunos");
        setPreferredSize(new java.awt.Dimension(960, 670));

        tpAbas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tpAbas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tpAbasStateChanged(evt);
            }
        });

        tbDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDados.setToolTipText("Clique para selecionar");
        tbDados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbDados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        spDados.setViewportView(tbDados);
        tbDados.getAccessibleContext().setAccessibleDescription("");

        tpAbas.addTab("Seleção", spDados);

        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ftCodigo.setEditable(false);
        ftCodigo.setAutoscrolls(false);
        ftCodigo.setEnabled(false);
        ftCodigo.setMinimumSize(new java.awt.Dimension(6, 25));

        rbMasculino.setForeground(new java.awt.Color(51, 51, 255));
        rbMasculino.setText("Masculino");
        rbMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMasculinoActionPerformed(evt);
            }
        });

        rbFeminino.setForeground(new java.awt.Color(51, 51, 255));
        rbFeminino.setText("Feminino");
        rbFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemininoActionPerformed(evt);
            }
        });

        try {
            MaskFormatter mfData = new MaskFormatter("##/##/####");
            mfData.setPlaceholderCharacter('_');

            ftNascimento = new JFormattedTextField(mfData);
        } catch (ParseException e) {}

        tfNacionalidade.setText("BRASILEIRA");

        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("           Foto do Aluno:");

        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText(" Código:");

        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText(" Nome:");

        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("                  Sexo:");

        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText(" Data de Nascimento:");

        jLabel23.setForeground(new java.awt.Color(21, 21, 255));
        jLabel23.setText(" Nacionalidade:");

        jLabel6.setForeground(new java.awt.Color(51, 51, 255));
        jLabel6.setText(" Nome do Pai:");

        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText(" Nome da Mãe:");

        rbPai.setForeground(new java.awt.Color(51, 51, 255));
        rbPai.setText("Pai");
        rbPai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPaiActionPerformed(evt);
            }
        });

        rbMae.setForeground(new java.awt.Color(51, 51, 255));
        rbMae.setText("Mãe");
        rbMae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMaeActionPerformed(evt);
            }
        });

        rbOutro.setForeground(new java.awt.Color(51, 51, 255));
        rbOutro.setText("Outro");
        rbOutro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbOutroActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText("Responsável Financeiro:");

        try{
            MaskFormatter mfCpf = new MaskFormatter("###.###.###-##");
            mfCpf.setPlaceholderCharacter('_');

            ftCpf = new JFormattedTextField(mfCpf);
        }catch (ParseException pe) {}

        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("   CPF Resp.Financeiro");

        tfOutro.setEnabled(false);

        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText(" Nome do Responsável Financeiro (quando não for o pai ou a mãe):");

        jLabel12.setForeground(new java.awt.Color(51, 51, 255));
        jLabel12.setText(" E-mail do Responsável:");

        jLabel13.setForeground(new java.awt.Color(51, 51, 255));
        jLabel13.setText(" Endereço do Aluno:");

        try{
            MaskFormatter mfCelular = new MaskFormatter("(##)#####-####");
            mfCelular.setPlaceholderCharacter('_');

            ftCelular = new JFormattedTextField(mfCelular);
        }catch (ParseException pe) {}

        jLabel14.setForeground(new java.awt.Color(51, 51, 255));
        jLabel14.setText(" Celular do Responsável:");

        jLabel15.setForeground(new java.awt.Color(51, 51, 255));
        jLabel15.setText(" Número:");

        jLabel16.setForeground(new java.awt.Color(51, 51, 255));
        jLabel16.setText(" Complemento:");

        jLabel17.setForeground(new java.awt.Color(51, 51, 255));
        jLabel17.setText(" Bairro:");

        try{
            MaskFormatter mfCep = new MaskFormatter("#####-###");
            mfCep.setPlaceholderCharacter('_');

            ftCep = new JFormattedTextField(mfCep);
        }catch(ParseException pe){}
        ftCep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ftCepActionPerformed(evt);
            }
        });

        jLabel18.setForeground(new java.awt.Color(51, 51, 255));
        jLabel18.setText(" CEP:");

        jLabel19.setForeground(new java.awt.Color(51, 51, 255));
        jLabel19.setText(" Cidade:");

        coUf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA",
            "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB",
            "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE",
            "TO"}));
coUf.setSelectedIndex(14);

jLabel20.setForeground(new java.awt.Color(51, 51, 255));
jLabel20.setText(" UF:");

try{
    MaskFormatter mfFone = new MaskFormatter("(##)####-####");
    mfFone.setPlaceholderCharacter('_');

    ftFone = new JFormattedTextField(mfFone);
    }catch(ParseException pe){}
    ftFone.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            ftFoneActionPerformed(evt);
        }
    });

    jLabel21.setForeground(new java.awt.Color(51, 51, 255));
    jLabel21.setText(" Telefone:");

    rbBolsistaSim.setForeground(new java.awt.Color(51, 51, 255));
    rbBolsistaSim.setText("Sim");
    rbBolsistaSim.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            rbBolsistaSimActionPerformed(evt);
        }
    });

    rbBolsistaNao.setForeground(new java.awt.Color(51, 51, 255));
    rbBolsistaNao.setText("Não");
    rbBolsistaNao.setSelected(true);
    rbBolsistaNao.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            rbBolsistaNaoActionPerformed(evt);
        }
    });

    jLabel22.setForeground(new java.awt.Color(51, 51, 255));
    jLabel22.setText("Bolsista:");

    rbAlergicoSim.setForeground(new java.awt.Color(51, 51, 255));
    rbAlergicoSim.setText("Sim");
    rbAlergicoSim.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            rbAlergicoSimActionPerformed(evt);
        }
    });

    rbAlergicoNao.setForeground(new java.awt.Color(51, 51, 255));
    rbAlergicoNao.setText("Não");

    jLabel24.setForeground(new java.awt.Color(51, 51, 255));
    jLabel24.setText("     Alérgico:");

    tfAlergia.setEnabled(false);

    jLabel25.setForeground(new java.awt.Color(51, 51, 255));
    jLabel25.setText(" Em caso positivo especifique a(s) alergia(s):");

    rbDoencaSim.setForeground(new java.awt.Color(51, 51, 255));
    rbDoencaSim.setText("Sim");
    rbDoencaSim.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            rbDoencaSimActionPerformed(evt);
        }
    });

    rbDoencaNao.setForeground(new java.awt.Color(51, 51, 255));
    rbDoencaNao.setText("Não");

    jLabel26.setForeground(new java.awt.Color(51, 51, 255));
    jLabel26.setText("Outro problema de saúde:");

    tfDoenca.setEnabled(false);

    jLabel27.setForeground(new java.awt.Color(51, 51, 255));
    jLabel27.setText("  Em caso positivo especifique:");

    rbManha.setForeground(new java.awt.Color(51, 51, 255));
    rbManha.setText("Manhã");
    rbManha.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            rbManhaActionPerformed(evt);
        }
    });

    rbTarde.setForeground(new java.awt.Color(51, 51, 255));
    rbTarde.setText("Tarde");
    rbTarde.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            rbTardeActionPerformed(evt);
        }
    });

    rbNoite.setForeground(new java.awt.Color(51, 51, 255));
    rbNoite.setText("Noite");
    rbNoite.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            rbNoiteActionPerformed(evt);
        }
    });

    rbIntegral.setForeground(new java.awt.Color(51, 51, 255));
    rbIntegral.setText("Integral");
    rbIntegral.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            rbIntegralActionPerformed(evt);
        }
    });

    jLabel28.setForeground(new java.awt.Color(51, 51, 255));
    jLabel28.setText("Turno:");

    jLabel29.setForeground(new java.awt.Color(51, 51, 255));
    jLabel29.setText("Turma:");

    btSalvar.setBackground(new java.awt.Color(51, 153, 255));
    btSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    btSalvar.setForeground(new java.awt.Color(255, 255, 0));
    btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisEscola/Salvar.png"))); // NOI18N
    btSalvar.setMnemonic('S');
    btSalvar.setText("  Salvar");
    btSalvar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
    btSalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btSalvar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btSalvarActionPerformed(evt);
        }
    });

    btAlterar.setBackground(new java.awt.Color(51, 153, 255));
    btAlterar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    btAlterar.setForeground(new java.awt.Color(255, 255, 0));
    btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisEscola/Alterar.png"))); // NOI18N
    btAlterar.setMnemonic('A');
    btAlterar.setText("Alterar");
    btAlterar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
    btAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btAlterar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btAlterarActionPerformed(evt);
        }
    });

    btExcluir.setBackground(new java.awt.Color(51, 153, 255));
    btExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    btExcluir.setForeground(new java.awt.Color(255, 51, 51));
    btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/SisEscola/Excluir.png"))); // NOI18N
    btExcluir.setMnemonic('E');
    btExcluir.setText("  Excluir");
    btExcluir.setBorder(javax.swing.BorderFactory.createCompoundBorder());
    btExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    btExcluir.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btExcluirActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout pnManutencaoLayout = new javax.swing.GroupLayout(pnManutencao);
    pnManutencao.setLayout(pnManutencaoLayout);
    pnManutencaoLayout.setHorizontalGroup(
        pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnManutencaoLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel2)
                .addComponent(jLabel14)
                .addComponent(ftCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfBairro, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(pnManutencaoLayout.createSequentialGroup()
                        .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnManutencaoLayout.createSequentialGroup()
                                .addComponent(rbAlergicoSim)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbAlergicoNao)))
                        .addGap(26, 26, 26))))
            .addGap(18, 18, 18)
            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnManutencaoLayout.createSequentialGroup()
                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfLogradouro)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfOutro)
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tfPai, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                        .addComponent(tfMae)
                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                            .addComponent(jLabel18)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel20))
                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                            .addComponent(ftCep, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfCidade)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(coUf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnManutencaoLayout.createSequentialGroup()
                                    .addComponent(ftNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(4, 4, 4))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnManutencaoLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnManutencaoLayout.createSequentialGroup()
                                    .addComponent(tfNacionalidade)
                                    .addContainerGap())))
                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnManutencaoLayout.createSequentialGroup()
                                    .addComponent(rbPai)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rbMae)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(rbOutro)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(ftCpf))
                                .addComponent(tfEmail)
                                .addGroup(pnManutencaoLayout.createSequentialGroup()
                                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfNumero)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                    .addGap(8, 8, 8)
                                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfComplemento)
                                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                                            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGap(0, 0, Short.MAX_VALUE))))
                                .addGroup(pnManutencaoLayout.createSequentialGroup()
                                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addComponent(jLabel9)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel10))
                                        .addComponent(jLabel12)
                                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                                            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ftFone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE))
                                            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(pnManutencaoLayout.createSequentialGroup()
                                                    .addGap(42, 42, 42)
                                                    .addComponent(rbBolsistaSim)
                                                    .addGap(18, 18, 18)
                                                    .addComponent(rbBolsistaNao))
                                                .addGroup(pnManutencaoLayout.createSequentialGroup()
                                                    .addGap(71, 71, 71)
                                                    .addComponent(jLabel22)))))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addContainerGap())))
                .addGroup(pnManutencaoLayout.createSequentialGroup()
                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                            .addComponent(jLabel25)
                            .addGap(18, 18, 18)
                            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnManutencaoLayout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(tfDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnManutencaoLayout.createSequentialGroup()
                                    .addComponent(jLabel26)
                                    .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnManutencaoLayout.createSequentialGroup()
                                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ftCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel4)
                                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                                            .addComponent(rbMasculino)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rbFeminino))
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(pnManutencaoLayout.createSequentialGroup()
                                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(tfAlergia, javax.swing.GroupLayout.PREFERRED_SIZE, 401, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnManutencaoLayout.createSequentialGroup()
                                            .addComponent(rbManha)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rbTarde)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(rbNoite)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(rbIntegral)
                                            .addGap(60, 60, 60))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnManutencaoLayout.createSequentialGroup()
                                            .addComponent(jLabel28)
                                            .addGap(165, 165, 165))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnManutencaoLayout.createSequentialGroup()
                                            .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(60, 60, 60)
                                            .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(40, 40, 40)))
                                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                                            .addGap(34, 34, 34)
                                            .addComponent(rbDoencaSim)
                                            .addGap(18, 18, 18)
                                            .addComponent(rbDoencaNao))
                                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                                            .addGap(10, 10, 10)
                                            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel29)
                                                .addComponent(coTurma, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                                            .addGap(20, 20, 20)
                                            .addComponent(btExcluir)))))
                            .addGap(0, 42, Short.MAX_VALUE)))
                    .addContainerGap())))
    );

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel1, jLabel2});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ftNascimento, jLabel7});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ftCodigo, jLabel3});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel4, tfNome});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel6, tfPai});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ftCelular, jLabel14, tfBairro});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ftCep, jLabel18});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {coUf, jLabel20});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel25, tfAlergia});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel27, tfDoenca});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAlterar, btExcluir, btSalvar});

    pnManutencaoLayout.setVerticalGroup(
        pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnManutencaoLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel2)
                .addComponent(jLabel3)
                .addComponent(jLabel4)
                .addComponent(jLabel5))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                .addGroup(pnManutencaoLayout.createSequentialGroup()
                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ftCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbMasculino)
                        .addComponent(rbFeminino))
                    .addGap(6, 6, 6)
                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel23)
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ftNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfPai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(8, 8, 8)
                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfMae, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbPai)
                        .addComponent(rbMae)
                        .addComponent(rbOutro)
                        .addComponent(ftCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12))
                    .addGap(4, 4, 4)
                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfOutro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnManutencaoLayout.createSequentialGroup()
                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(pnManutencaoLayout.createSequentialGroup()
                    .addComponent(jLabel14)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(ftCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ftCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(coUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ftFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(rbBolsistaSim)
                .addComponent(rbBolsistaNao))
            .addGap(13, 13, 13)
            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel24)
                .addComponent(jLabel25)
                .addComponent(jLabel26)
                .addComponent(jLabel27))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbAlergicoSim)
                .addComponent(rbAlergicoNao)
                .addComponent(tfAlergia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(rbDoencaSim)
                .addComponent(rbDoencaNao)
                .addComponent(tfDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel28)
                .addComponent(jLabel29))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(rbTarde)
                .addComponent(rbManha)
                .addComponent(rbNoite)
                .addComponent(rbIntegral)
                .addComponent(coTurma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btExcluir))
            .addContainerGap())
    );

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btAlterar, btExcluir, btSalvar});

    tpAbas.addTab("Manutenção", pnManutencao);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(tpAbas)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(tpAbas)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents
    protected void atualizarGrade() {
        try {
            ResultSet rs = new AlunoDAO().carregarGrade();
            tbDados.setModel(new ModeloGrade(rs, new String[]{"Código", "Nome", "Turno", "Turma"}));
            tbDados.getColumnModel().getColumn(0).setMaxWidth(50);
        } catch (Exception e) {
            showMessageDialog(this, e.getMessage(), "Erro", ERROR_MESSAGE);
        }
    }

    public void popularTurma() {
        try {
            Statement stm = ce.getConexao().createStatement();
            ResultSet rs = stm.executeQuery("SELECT * FROM TURMA ORDER BY NOME");

            rs.first();
            coTurma.removeAllItems();
            do {
                coTurma.addItem(rs.getString("NOME"));
            } while (rs.next());
        } catch (SQLException ex) {
            showMessageDialog(this, "Erro ao preencher turma!", "Erro", ERROR_MESSAGE);
        }
    }

    class MouseHandler extends MouseAdapter {

        public void mouseReleased(MouseEvent e) {
            if (e.getButton() != MouseEvent.BUTTON1) {
                return;
            }
            JTable tb = (JTable) e.getSource();
            int lin = tb.getSelectionModel().getMinSelectionIndex();
            String codigo = tb.getModel().getValueAt(lin, 0).toString();

            try {
                carregarRegistro(codigo);
                tpAbas.setSelectedComponent(pnManutencao);
                tfNome.requestFocus();
            } catch (Exception ex) {
                showMessageDialog(APAluno.this, ex.getMessage(), "Erro", ERROR_MESSAGE);
            }
        }
    }

    protected void incluir() {
        Aluno a = new Aluno();
        a.setNome(tfNome.getText());
        a.setSexo(sexo);
        a.setNascimento(ftNascimento.getText());
        a.setNacionalidade(tfNacionalidade.getText());
        a.setPai(tfPai.getText());
        a.setMae(tfMae.getText());
        a.setRespFinanceiro(responsavel);
        a.setCpfRespFinan(ftCpf.getText());
        a.setNomeRespFinan(tfOutro.getText());
        a.setEmail(tfEmail.getText());
        a.setCelular(ftCelular.getText());
        a.setLogradouro(tfLogradouro.getText());
        a.setNumero(tfNumero.getText());
        a.setComplemento(tfComplemento.getText());
        a.setBairro(tfBairro.getText());
        a.setCep(ftCep.getText());
        a.setCidade(tfCidade.getText());
        String uf = (String) coUf.getSelectedItem();
        a.setUf(uf);
        a.setFone(ftFone.getText());
        a.setBolsista(bolsista);
        a.setAlergia(alergico);
        a.setTipoAlergia(tfAlergia.getText());
        a.setDoenca(doenca);
        a.setTipoDoenca(tfDoenca.getText());
        a.setTurno(turno);
        int i = coTurma.getSelectedIndex();
        a.setIdTurma(i);
        String t = (String) coTurma.getSelectedItem();
        a.setTurma(t);

        try {
            new AlunoDAO().incluir(a);
            atualizarGrade();
            tpAbas.setSelectedIndex(0);
        } catch (Exception ex) {
            showMessageDialog(this, "Erro ao incluir aluno! " + ex.getMessage(), "Erro", ERROR_MESSAGE);
        }
    }

    protected void alterar() {
        Aluno a = new Aluno();
        a.setCodalu(ftCodigo.getText());
        a.setNome(tfNome.getText());
        if (rbMasculino.isSelected()) {
            sexo = "MASCULINO";
        } else if (rbFeminino.isSelected()) {
            sexo = "FEMININO";
        }
        a.setSexo(sexo);
        a.setNascimento(ftNascimento.getText());
        a.setNacionalidade(tfNacionalidade.getText());
        a.setPai(tfPai.getText());
        a.setMae(tfMae.getText());
        if (rbPai.isSelected()) {
            responsavel = "PAI";
        } else if (rbMae.isSelected()) {
            responsavel = "MÃE";
        } else {
            responsavel = "OUTRO";
        }
        a.setRespFinanceiro(responsavel);
        a.setCpfRespFinan(ftCpf.getText());
        a.setNomeRespFinan(tfOutro.getText());
        a.setEmail(tfEmail.getText());
        a.setCelular(ftCelular.getText());
        a.setLogradouro(tfLogradouro.getText());
        a.setNumero(tfNumero.getText());
        a.setComplemento(tfComplemento.getText());
        a.setBairro(tfBairro.getText());
        a.setCep(ftCep.getText());
        a.setCidade(tfCidade.getText());
        String uf = (String) coUf.getSelectedItem();
        a.setUf(uf);
        a.setFone(ftFone.getText());
        if (rbBolsistaSim.isSelected()) {
            bolsista = "SIM";
        } else {
            bolsista = "NÃO";
        }
        a.setBolsista(bolsista);
        if (rbAlergicoSim.isSelected()) {
            alergico = "SIM";
        } else {
            alergico = "NÃO";
        }
        a.setAlergia(alergico);
        a.setTipoAlergia(tfAlergia.getText());
        if (rbDoencaSim.isSelected()) {
            doenca = "SIM";
        } else {
            doenca = "NÃO";
        }
        a.setDoenca(doenca);
        a.setTipoDoenca(tfDoenca.getText());
        if (rbManha.isSelected()) {
            turno = "MANHÃ";
        } else if (rbTarde.isSelected()) {
            turno = "TARDE";
        } else if (rbNoite.isSelected()) {
            turno = "NOITE";
        } else {
            turno = "INTEGRAL";
        }
        a.setTurno(turno);
        int i = coTurma.getSelectedIndex();
        a.setIdTurma(i);
        Object t = coTurma.getSelectedItem();
        a.setTurma(String.valueOf(t));

        try {
            new AlunoDAO().alterar(a);
            atualizarGrade();
            tpAbas.setSelectedIndex(0);
        } catch (Exception ex) {
            showMessageDialog(this, ex.getMessage(), "Erro", ERROR_MESSAGE);
        }
    }

    protected void excluir() {
        try {
            int codigo = Integer.parseInt(ftCodigo.getText());
            new AlunoDAO().excluir(codigo);
            ModeloGrade dtm = (ModeloGrade) tbDados.getModel();
            dtm.removeRow(tbDados.getSelectedRow());
            tpAbas.setSelectedIndex(0);
            atualizarGrade();
        } catch (Exception ex) {
            showMessageDialog(this, ex.getMessage(), "Erro", ERROR_MESSAGE);
        }
    }

    protected void carregarRegistro(String codigo) throws Exception {
        Aluno a = new AlunoDAO().pesquisar(codigo);
        ftCodigo.setText(String.valueOf(a.getCodalu()));
        tfNome.setText(a.getNome());
        String str = a.getSexo();
        if (str.length() == 9) {
            rbMasculino.setSelected(true);
        } else if (str.length() == 8) {
            rbFeminino.setSelected(true);
        }
        tfPai.setText(a.getPai());
        ftNascimento.setText(a.getNascimentoFmt());
        tfNacionalidade.setText(a.getNacionalidade());
        tfMae.setText(a.getMae());
        str = a.getRespFinanceiro();
        if (str.equalsIgnoreCase("PAI")) {
            rbPai.setSelected(true);
            tfOutro.setEnabled(false);
        } else if (str.equalsIgnoreCase("MÃE")) {
            rbMae.setSelected(true);
            tfOutro.setEnabled(false);
        } else {
            rbOutro.setSelected(true);
            tfOutro.setEnabled(true);
        }
        ftCpf.setText(a.getCpfRespFinan());
        tfOutro.setText(a.getNomeRespFinan());
        tfEmail.setText(a.getEmail());
        ftCelular.setText(a.getCelular());
        tfLogradouro.setText(a.getLogradouro());
        tfNumero.setText(String.valueOf(a.getNumero()));
        tfComplemento.setText(a.getComplemento());
        tfBairro.setText(a.getBairro());
        ftCep.setText(a.getCep());
        tfCidade.setText(a.getCidade());
        coUf.setSelectedItem(a.getUf());
        ftFone.setText(a.getFone());
        str = a.getBolsista();
        if (str.equalsIgnoreCase("SIM")) {
            rbBolsistaSim.setSelected(true);
        } else {
            rbBolsistaNao.setSelected(true);
        }
        str = a.getAlergia();
        if (str.equalsIgnoreCase("SIM")) {
            rbAlergicoSim.setSelected(true);
            tfAlergia.setEnabled(true);
        } else {
            rbAlergicoNao.setSelected(true);
            tfAlergia.setEnabled(false);
        }
        tfAlergia.setText(a.getTipoAlergia());
        str = a.getDoenca();
        if (str.equalsIgnoreCase("SIM")) {
            rbDoencaSim.setSelected(true);
            tfDoenca.setEnabled(true);
        } else {
            rbDoencaNao.setSelected(true);
            tfDoenca.setEnabled(false);
        }
        tfDoenca.setText(a.getTipoDoenca());
        str = a.getTurno();
        if (str.equalsIgnoreCase("MANHÃ")) {
            rbManha.setSelected(true);
        } else if (str.equalsIgnoreCase("TARDE")) {
            rbTarde.setSelected(true);
        } else if (str.equalsIgnoreCase("NOITE")) {
            rbNoite.setSelected(true);
        } else {
            rbIntegral.setSelected(true);
        }
        str = a.getTurma();
        coTurma.setSelectedItem(str);
    }

    private void rbMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMasculinoActionPerformed
        // TODO add your handling code here:
        if (rbMasculino.isSelected()) {
            sexo = "MASCULINO";
        }
    }//GEN-LAST:event_rbMasculinoActionPerformed

    private void rbFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemininoActionPerformed
        // TODO add your handling code here:
        if (rbFeminino.isSelected()) {
            sexo = "FEMININO";
        }
    }//GEN-LAST:event_rbFemininoActionPerformed

    private void rbAlergicoSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbAlergicoSimActionPerformed
        // TODO add your handling code here:
        if (rbAlergicoSim.isSelected()) {
            tfAlergia.setEnabled(true);
            alergico = "SIM";
        }
    }//GEN-LAST:event_rbAlergicoSimActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == btSalvar) {
            incluir();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == btAlterar) {
            alterar();
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == btExcluir) {
            int opcao = showOptionDialog(this, "Tem certeza que deseja excluir esse aluno?", "Confirme", 0,
                    QUESTION_MESSAGE, null, new String[]{"Sim", "Não"}, "Não");
            switch (opcao) {
                case -1:
                    return;
                case 0:
                    excluir();
                    break;               
            }
        }
    }//GEN-LAST:event_btExcluirActionPerformed

    private void rbOutroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbOutroActionPerformed
        // TODO add your handling code here:
        if (rbOutro.isSelected()) {
            tfOutro.setEnabled(true);
            responsavel = "OUTRO";
        }
    }//GEN-LAST:event_rbOutroActionPerformed

    private void rbPaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPaiActionPerformed
        // TODO add your handling code here:
        if (rbPai.isSelected()) {
            tfOutro.setEnabled(false);
            responsavel = "PAI";
        }
    }//GEN-LAST:event_rbPaiActionPerformed

    private void rbMaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMaeActionPerformed
        // TODO add your handling code here:
        if (rbMae.isSelected()) {
            tfOutro.setEnabled(false);
            responsavel = "MÃE";
        }
    }//GEN-LAST:event_rbMaeActionPerformed

    private void rbDoencaSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbDoencaSimActionPerformed
        // TODO add your handling code here:
        if (rbDoencaSim.isSelected()) {
            tfDoenca.setEnabled(true);
            doenca = "SIM";
        }
    }//GEN-LAST:event_rbDoencaSimActionPerformed

    private void rbBolsistaSimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBolsistaSimActionPerformed
        // TODO add your handling code here:
        if (rbBolsistaSim.isSelected()) {
            bolsista = "SIM";
        }
    }//GEN-LAST:event_rbBolsistaSimActionPerformed

    private void rbManhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbManhaActionPerformed
        // TODO add your handling code here:
        if (rbManha.isSelected()) {
            turno = "MANHÃ";
        }
    }//GEN-LAST:event_rbManhaActionPerformed

    private void rbTardeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbTardeActionPerformed
        // TODO add your handling code here:
        if (rbTarde.isSelected()) {
            turno = "TARDE";
        }
    }//GEN-LAST:event_rbTardeActionPerformed

    private void rbNoiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbNoiteActionPerformed
        // TODO add your handling code here:
        if (rbNoite.isSelected()) {
            turno = "NOITE";
        }
    }//GEN-LAST:event_rbNoiteActionPerformed

    private void rbIntegralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbIntegralActionPerformed
        // TODO add your handling code here:
        if (rbIntegral.isSelected()) {
            turno = "INTEGRAL";
        }
    }//GEN-LAST:event_rbIntegralActionPerformed

    private void tpAbasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tpAbasStateChanged
        // TODO add your handling code here:
        if (tpAbas.getSelectedIndex() != 0) {
            return;
        }
        for (int i = 0; i < pnManutencao.getComponentCount(); i++) {
            if (pnManutencao.getComponent(i) instanceof JTextComponent) {
                ((JTextComponent) pnManutencao.getComponent(i)).setText("");
            }
            if (pnManutencao.getComponent(i) instanceof JComboBox) {
                ((JComboBox) pnManutencao.getComponent(i)).setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_tpAbasStateChanged

    private void ftFoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftFoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftFoneActionPerformed

    private void ftCepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ftCepActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ftCepActionPerformed

    private void rbBolsistaNaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbBolsistaNaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbBolsistaNaoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgAlergico;
    private javax.swing.ButtonGroup bgBolsista;
    private javax.swing.ButtonGroup bgResponsavel;
    private javax.swing.ButtonGroup bgSaude;
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.ButtonGroup bgTurno;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox coTurma;
    private javax.swing.JComboBox coUf;
    private javax.swing.JFormattedTextField ftCelular;
    private javax.swing.JFormattedTextField ftCep;
    private javax.swing.JFormattedTextField ftCodigo;
    private javax.swing.JFormattedTextField ftCpf;
    private javax.swing.JFormattedTextField ftFone;
    private javax.swing.JFormattedTextField ftNascimento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnManutencao;
    private javax.swing.JRadioButton rbAlergicoNao;
    private javax.swing.JRadioButton rbAlergicoSim;
    private javax.swing.JRadioButton rbBolsistaNao;
    private javax.swing.JRadioButton rbBolsistaSim;
    private javax.swing.JRadioButton rbDoencaNao;
    private javax.swing.JRadioButton rbDoencaSim;
    private javax.swing.JRadioButton rbFeminino;
    private javax.swing.JRadioButton rbIntegral;
    private javax.swing.JRadioButton rbMae;
    private javax.swing.JRadioButton rbManha;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JRadioButton rbNoite;
    private javax.swing.JRadioButton rbOutro;
    private javax.swing.JRadioButton rbPai;
    private javax.swing.JRadioButton rbTarde;
    private javax.swing.JScrollPane spDados;
    private javax.swing.JTable tbDados;
    private javax.swing.JTextField tfAlergia;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfComplemento;
    private javax.swing.JTextField tfDoenca;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfLogradouro;
    private javax.swing.JTextField tfMae;
    private javax.swing.JTextField tfNacionalidade;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfOutro;
    private javax.swing.JTextField tfPai;
    private javax.swing.JTabbedPane tpAbas;
    // End of variables declaration//GEN-END:variables
}
