DROP DATABASE IF EXISTS escola;

CREATE DATABASE escola;

USE escola;

CREATE TABLE ALUNO(
  CODIGO INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(40) NOT NULL,
  NASCIMENTO DATE NOT NULL,
  PAI VARCHAR(40) NOT NULL,
  MAE VARCHAR(40) NOT NULL,
  RESP_FINANC VARCHAR(40) NOT NULL,
  LOGRADOURO VARCHAR(40) NOT NULL,
  NUMERO SMALLINT(5) NOT NULL,
  COMPLEMENTO VARCHAR(10) NOT NULL,
  BAIRRO VARCHAR(20) NOT NULL,
  CEP CHAR(8) NOT NULL,
  CIDADE VARCHAR(20) NOT NULL,
  UF CHAR(2) NOT NULL,
  FONE CHAR(10) NOT NULL,
  CELULAR_RESP CHAR(11) NOT NULL,
  EMAIL_RESP VARCHAR(20) NOT NULL,
  BOLSISTA CHAR(1) NOT NULL,
  TURNO CHAR(5) NOT NULL,
  PRIMARY KEY(CODIGO)
) ENGINE = INNODB;

CREATE TABLE DISCIPLINA(
  CODIGO INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(20) NOT NULL,
  PROFESSOR VARCHAR(40) NOT NULL,
  PRIMARY KEY(CODIGO)
) ENGINE = INNODB;

CREATE TABLE TURMA(
  CODIGO INT NOT NULL AUTO_INCREMENT,
  NOME VARCHAR(15) NOT NULL,
  TURNO CHAR(5) NOT NULL,
  ALUNOS VARCHAR(40) NOT NULL,
  PRIMARY KEY(CODIGO)
) ENGINE = INNODB;

CREATE TABLE FUNCIONARIO(
  CODIGO INT NOT NULL AUTO_INCREMENT,
  NASCIMENTO DATE NOT NULL,
  CPF CHAR(11) NOT NULL,
  RG CHAR(10) NOT NULL,
  ORG_EXP CHAR(5) NOT NULL,
  CTPS CHAR(8) NOT NULL,
  SERIE CHAR(8) NOT NULL,
  ADMISSAO DATE NOT NULL,
  DEMISSAO DATE NOT NULL,
  LOGRADOURO VARCHAR(40) NOT NULL,
  NUMERO SMALLINT(5) NOT NULL,
  COMPLEMENTO VARCHAR(10) NOT NULL,
  BAIRRO VARCHAR(20) NOT NULL,
  CEP CHAR(8) NOT NULL,
  CIDADE VARCHAR(20) NOT NULL,
  UF CHAR(2) NOT NULL,
  FONE CHAR(10) NOT NULL,
  CELULAR CHAR(11) NOT NULL,
  DEPARTAMENTO VARCHAR(10) NOT NULL,
  FUNCAO VARCHAR(10) NOT NULL,
  SALARIO DECIMAL(10, 2) NOT NULL,
  PRIMARY KEY(CODIGO)
) ENGINE = INNODB;

CREATE TABLE PROFESSOR(
  CODPROF INT(4) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOMEPROF VARCHAR(40) NOT NULL  
); 

