/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.sisescola.view;

import br.com.sisescola.accessories.ConexaoEscola;
import br.com.sisescola.dao.FuncionarioDAO;
import br.com.sisescola.transferencia.Funcionario;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFormattedTextField;
import static javax.swing.JOptionPane.*;
import javax.swing.JTable;
import javax.swing.text.JTextComponent;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Vinicius
 */
public class APFuncionario1 extends javax.swing.JInternalFrame {
    private ConexaoEscola ce;
    private String sexo;
        
    /**
     * Creates new form APFuncionario1
     */
    public APFuncionario1() throws Exception {
        ce = new ConexaoEscola();
        initComponents();
        popularDpto();       
        
        tbDados.addMouseListener(new APFuncionario1.MouseHandler());
                
        tpAbas.setMnemonicAt(0, 'S');
        tpAbas.setMnemonicAt(1, 'M');   
        
        atualizarGrade();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    protected void atualizarGrade(){
        try {
            ResultSet rs = new FuncionarioDAO().carregarGrade();
            tbDados.setModel(new ModeloGrade(rs,new String[]{"Código","Nome","CPF","Departamento","Função","Salário"}));
            tbDados.getColumnModel().getColumn(0).setMaxWidth(50);
            tbDados.getColumnModel().getColumn(5).setMaxWidth(70);
        } catch (Exception e) {
            showMessageDialog(this, e.getMessage(),"Erro",ERROR_MESSAGE);
        }
    }    
    
    public void popularDpto() {
        try {
            Statement stm = ce.getConexao().createStatement();
            ResultSet rs = stm.executeQuery("SELECT * FROM DEPTO ORDER BY NOME");

            rs.first();
            coDpto.removeAllItems();
            do {
                coDpto.addItem(rs.getString("NOME"));
            } while (rs.next());
        } catch (SQLException ex) {
            showMessageDialog(this, "Erro ao preencher departamento!", "Erro", ERROR_MESSAGE);
        }
    }      
    
    class MouseHandler extends MouseAdapter{
        public void mouseReleased(MouseEvent e){
            if(e.getButton() != MouseEvent.BUTTON1) return;
            JTable tb = (JTable)e.getSource();
            int lin = tb.getSelectionModel().getMinSelectionIndex();
            String codigo = tb.getModel().getValueAt(lin, 0).toString();

            try {
                carregarRegistro(codigo);
                tpAbas.setSelectedComponent(pnManutencao);
                tfNome.requestFocus();
            } catch (Exception ex) {
                showMessageDialog(APFuncionario1.this, ex.getMessage(),"Erro", ERROR_MESSAGE);
            }
        }
    }
    
    protected void incluir() {
        Funcionario f = new Funcionario();
        f.setNome(tfNome.getText());
        f.setSexo(sexo);
        f.setNascimento(ftNascimento.getText());
        f.setNacionalidade(tfNacionalidade.getText());
        f.setCpf(ftCpf.getText());
        f.setRg(tfRg.getText());
        f.setOrgexp(ftOrgexp.getText());
        f.setCtps(tfCtps.getText());
        f.setSerie(tfSerie.getText());
        f.setAdmissao(ftAdmissao.getText());
        String data = ftDemissao.getText();
        f.setLogradouro(tfLogradouro.getText());
        f.setNumero(tfNumero.getText());
        f.setComplemento(tfComplemento.getText());
        f.setBairro(tfBairro.getText());
        f.setCep(ftCep.getText());
        f.setCidade(tfCidade.getText());
        String uf = (String) coUf.getSelectedItem();
        f.setUf(uf);
        f.setFone(ftFone.getText());
        f.setCelular(ftCelular.getText());
        int i = coDpto.getSelectedIndex();
        f.setIdDpto(i);
        Object dpto = coDpto.getSelectedItem();
        f.setNome_dpto(String.valueOf(dpto));
        f.setFuncao(tfFuncao.getText());
        f.setSalario(ftSalario.getText());

        try {
            new FuncionarioDAO().incluir(f);
            atualizarGrade();
            tpAbas.setSelectedIndex(0);
        } catch (Exception ex) {
            showMessageDialog(this, "Erro ao incluir funcionário!" + ex.getMessage(), "Erro", ERROR_MESSAGE);
        }
    }
    
    protected void alterar(){
        Funcionario f = new Funcionario();
        f.setCodfun(ftCodigo.getText());
        f.setNome(tfNome.getText());
        if(rbMasculino.isSelected())sexo = "Masculino";
        else if(rbFeminino.isSelected())sexo = "Feminino";
        f.setSexo(sexo);
        f.setNascimento(ftNascimento.getText());
        f.setNacionalidade(tfNacionalidade.getText());
        f.setCpf(ftCpf.getText());
        f.setRg(tfRg.getText());
        f.setOrgexp(ftOrgexp.getText());
        f.setCtps(tfCtps.getText());
        f.setSerie(tfSerie.getText());
        f.setAdmissao(ftAdmissao.getText());
        f.setDemissao(ftDemissao.getText());
        f.setLogradouro(tfLogradouro.getText());
        f.setNumero(tfNumero.getText());
        f.setComplemento(tfComplemento.getText());
        f.setBairro(tfBairro.getText());
        f.setCep(ftCep.getText());
        f.setCidade(tfCidade.getText());
        String uf = (String)coUf.getSelectedItem();
        f.setUf(uf);
        f.setFone(ftFone.getText());
        f.setCelular(ftCelular.getText());
        int i = coDpto.getSelectedIndex();
        f.setIdDpto(i);
        Object dpto = coDpto.getSelectedItem();
        f.setNome_dpto(String.valueOf(dpto));
        f.setFuncao(tfFuncao.getText());
        f.setSalario(ftSalario.getText());

        try {
            new FuncionarioDAO().alterar(f);
            atualizarGrade();
            tpAbas.setSelectedIndex(0);
        } catch (Exception ex) {
            showMessageDialog(this, ex.getMessage(),"Erro",ERROR_MESSAGE);
        }
    }
    
    protected void excluir(){
        try {
            int codigo = Integer.parseInt(ftCodigo.getText());
            new FuncionarioDAO().excluir(codigo);
            ModeloGrade dtm = (ModeloGrade)tbDados.getModel();
            dtm.removeRow(tbDados.getSelectedRow());
            tpAbas.setSelectedIndex(0);
            atualizarGrade();
        } catch (Exception ex) {
            showMessageDialog(this, ex.getMessage(),"Erro",ERROR_MESSAGE);
        }
    }
    
    protected void carregarRegistro(String codigo)throws Exception{
        Funcionario f = new FuncionarioDAO().pesquisar(codigo);
        ftCodigo.setText(String.valueOf(f.getCodfun()));
        tfNome.setText(f.getNome());
        String str = f.getSexo();
        if(str.length() == 9)
        rbMasculino.setSelected(true);
        else if(str.length() == 8)
        rbFeminino.setSelected(true);
        ftNascimento.setText(f.getNascimentoFmt());
        tfNacionalidade.setText(f.getNacionalidade());
        ftCpf.setText(f.getCpf());
        tfRg.setText(f.getRg());
        ftOrgexp.setText(f.getOrgexp());
        tfCtps.setText(f.getCtps());
        tfSerie.setText(f.getSerie());
        ftAdmissao.setText(f.getAdmissaoFmt());
        ftDemissao.setText(f.getDemissaoFmt());
        tfLogradouro.setText(f.getLogradouro());
        tfNumero.setText(String.valueOf(f.getNumero()));
        tfComplemento.setText(f.getComplemento());
        tfBairro.setText(f.getBairro());
        ftCep.setText(f.getCep());
        tfCidade.setText(f.getCidade());
        coUf.setSelectedItem(f.getUf());
        ftFone.setText(f.getFone());
        ftCelular.setText(f.getCelular());
        String s = f.getNome_dpto();
        coDpto.setSelectedItem(s);
        tfFuncao.setText(f.getFuncao());
        ftSalario.setText(f.getSalarioFmt());
    } 
    

    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        tpAbas = new javax.swing.JTabbedPane();
        spDados = new javax.swing.JScrollPane();
        tbDados = new javax.swing.JTable();
        pnManutencao = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        ftCodigo = new javax.swing.JFormattedTextField(new Integer(0));
        tfNome = new javax.swing.JTextField();
        rbMasculino = new javax.swing.JRadioButton();
        rbFeminino = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ftNascimento = new javax.swing.JFormattedTextField();
        tfNacionalidade = new javax.swing.JTextField();
        tfNacionalidade.setText("BRASILEIRA");
        ftCpf = new javax.swing.JFormattedTextField();
        tfRg = new javax.swing.JTextField();
        ftOrgexp = new javax.swing.JFormattedTextField();
        tfCtps = new javax.swing.JTextField();
        tfSerie = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        ftAdmissao = new javax.swing.JFormattedTextField();
        ftDemissao = new javax.swing.JFormattedTextField();
        tfLogradouro = new javax.swing.JTextField();
        tfNumero = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        tfComplemento = new javax.swing.JTextField();
        tfBairro = new javax.swing.JTextField();
        ftCep = new javax.swing.JFormattedTextField();
        tfCidade = new javax.swing.JTextField();
        coUf = new javax.swing.JComboBox();
        ftFone = new javax.swing.JFormattedTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        ftCelular = new javax.swing.JFormattedTextField();
        coDpto = new javax.swing.JComboBox();
        tfFuncao = new javax.swing.JTextField();
        ftSalario = new javax.swing.JFormattedTextField(new Double(0));
        btSalvar = new javax.swing.JButton();
        btAlterar = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();

        bgSexo.add(rbMasculino);
        bgSexo.add(rbFeminino);

        setClosable(true);
        setIconifiable(true);
        setResizable(true);
        setTitle("Cadastro de Funcionários");
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(950, 500));

        tpAbas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tpAbas.setPreferredSize(new java.awt.Dimension(920, 450));
        tpAbas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tpAbasStateChanged(evt);
            }
        });

        tbDados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDados.setToolTipText("Clique para selecionar");
        tbDados.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tbDados.setName(""); // NOI18N
        tbDados.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        spDados.setViewportView(tbDados);
        tbDados.getAccessibleContext().setAccessibleDescription("");

        tpAbas.addTab("Seleção", spDados);

        pnManutencao.setPreferredSize(new java.awt.Dimension(950, 450));

        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Foto do Funcionário:");

        jLabel3.setForeground(new java.awt.Color(51, 51, 255));
        jLabel3.setText(" Código:");

        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText(" Nome:");

        jLabel5.setForeground(new java.awt.Color(51, 51, 255));
        jLabel5.setText("                        Sexo:");

        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        ftCodigo.setAutoscrolls(false);
        ftCodigo.setEnabled(false);
        ftCodigo.setMinimumSize(new java.awt.Dimension(6, 25));

        rbMasculino.setForeground(new java.awt.Color(51, 51, 255));
        rbMasculino.setText("Masculino");
        rbMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbMasculinoActionPerformed(evt);
            }
        });

        rbFeminino.setForeground(new java.awt.Color(51, 51, 255));
        rbFeminino.setText("Feminino");
        rbFeminino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbFemininoActionPerformed(evt);
            }
        });

        jLabel7.setForeground(new java.awt.Color(51, 51, 255));
        jLabel7.setText(" Data de Nascimento:");

        jLabel23.setForeground(new java.awt.Color(21, 21, 255));
        jLabel23.setText(" Nacionalidade:");

        jLabel8.setForeground(new java.awt.Color(51, 51, 255));
        jLabel8.setText(" CPF:");

        jLabel9.setForeground(new java.awt.Color(51, 51, 255));
        jLabel9.setText(" RG:");

        jLabel10.setForeground(new java.awt.Color(51, 51, 255));
        jLabel10.setText("Órg.Expedidor:");

        jLabel11.setForeground(new java.awt.Color(51, 51, 255));
        jLabel11.setText(" CTPS:");

        jLabel12.setForeground(new java.awt.Color(51, 51, 255));
        jLabel12.setText(" Série:");

        try {
            MaskFormatter mfData = new MaskFormatter("##/##/####");
            mfData.setPlaceholderCharacter('_');

            ftNascimento = new JFormattedTextField(mfData);
        } catch (ParseException e) {}

        try{
            MaskFormatter mfCpf = new MaskFormatter("###.###.###-##");
            mfCpf.setPlaceholderCharacter('_');

            ftCpf = new JFormattedTextField(mfCpf);
        }catch (ParseException pe) {}

        try {
            MaskFormatter mfOrgexp = new MaskFormatter("UUU/UU");
            mfOrgexp.setPlaceholderCharacter('_');

            ftOrgexp = new JFormattedTextField(mfOrgexp);
        } catch (ParseException e) {}

        jLabel13.setForeground(new java.awt.Color(51, 51, 255));
        jLabel13.setText(" Data da Admissão:");

        jLabel14.setForeground(new java.awt.Color(51, 51, 255));
        jLabel14.setText(" Data da Demissão:");

        jLabel15.setForeground(new java.awt.Color(51, 51, 255));
        jLabel15.setText(" Endereço:");

        jLabel16.setForeground(new java.awt.Color(51, 51, 255));
        jLabel16.setText(" Número:");

        try{
            MaskFormatter mfAdmissao = new MaskFormatter("##/##/####");
            mfAdmissao.setPlaceholderCharacter('_');

            ftAdmissao = new JFormattedTextField(mfAdmissao);
        }catch(ParseException pe){}

        try{
            MaskFormatter mfDemissao = new MaskFormatter("##/##/####");
            mfDemissao.setPlaceholderCharacter('_');

            ftDemissao = new JFormattedTextField(mfDemissao);
        }catch(ParseException pe){}

        jLabel17.setForeground(new java.awt.Color(21, 21, 255));
        jLabel17.setText(" Complemento: ");

        jLabel18.setForeground(new java.awt.Color(21, 21, 255));
        jLabel18.setText(" Bairro:");

        jLabel19.setForeground(new java.awt.Color(21, 21, 255));
        jLabel19.setText(" CEP:");

        jLabel20.setForeground(new java.awt.Color(21, 21, 255));
        jLabel20.setText(" Cidade:");

        jLabel21.setForeground(new java.awt.Color(21, 21, 255));
        jLabel21.setText(" UF:");

        jLabel22.setForeground(new java.awt.Color(21, 21, 255));
        jLabel22.setText(" Telefone:");

        try{
            MaskFormatter mfCep = new MaskFormatter("#####-###");
            mfCep.setPlaceholderCharacter('_');

            ftCep = new JFormattedTextField(mfCep);
        }catch(ParseException pe){}

        coUf.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "AC", "AL", "AP", "AM", "BA",
            "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB",
            "PR", "PE", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE",
            "TO"}));
coUf.setSelectedIndex(14);

try{
    MaskFormatter mfFone = new MaskFormatter("(##)####-####");
    mfFone.setPlaceholderCharacter('_');

    ftFone = new JFormattedTextField(mfFone);
    }catch(ParseException pe){}

    jLabel24.setForeground(new java.awt.Color(21, 21, 255));
    jLabel24.setText(" Celular:");

    jLabel25.setForeground(new java.awt.Color(21, 21, 255));
    jLabel25.setText("  Departamento:");

    jLabel26.setForeground(new java.awt.Color(21, 21, 255));
    jLabel26.setText(" Função:");

    jLabel27.setForeground(new java.awt.Color(21, 21, 255));
    jLabel27.setText(" Salário Bruto:");

    try{
        MaskFormatter mfCelular = new MaskFormatter("(##)#####-####");
        mfCelular.setPlaceholderCharacter('_');

        ftCelular = new JFormattedTextField(mfCelular);
    }catch (ParseException pe) {}

    btSalvar.setBackground(new java.awt.Color(51, 153, 255));
    btSalvar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    btSalvar.setForeground(new java.awt.Color(255, 255, 0));
    btSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sisescola/view/Salvar.png"))); // NOI18N
    btSalvar.setMnemonic('S');
    btSalvar.setText("  Salvar");
    btSalvar.setToolTipText("");
    btSalvar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
    btSalvar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btSalvarActionPerformed(evt);
        }
    });

    btAlterar.setBackground(new java.awt.Color(51, 153, 255));
    btAlterar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    btAlterar.setForeground(new java.awt.Color(255, 255, 0));
    btAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sisescola/view/Alterar.png"))); // NOI18N
    btAlterar.setMnemonic('A');
    btAlterar.setText("Alterar");
    btAlterar.setBorder(javax.swing.BorderFactory.createCompoundBorder());
    btAlterar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btAlterarActionPerformed(evt);
        }
    });

    btExcluir.setBackground(new java.awt.Color(51, 153, 255));
    btExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
    btExcluir.setForeground(new java.awt.Color(255, 51, 51));
    btExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/sisescola/view/Excluir.png"))); // NOI18N
    btExcluir.setMnemonic('E');
    btExcluir.setText("  Excluir");
    btExcluir.setBorder(javax.swing.BorderFactory.createCompoundBorder());
    btExcluir.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btExcluirActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout pnManutencaoLayout = new javax.swing.GroupLayout(pnManutencao);
    pnManutencao.setLayout(pnManutencaoLayout);
    pnManutencaoLayout.setHorizontalGroup(
        pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnManutencaoLayout.createSequentialGroup()
            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnManutencaoLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(pnManutencaoLayout.createSequentialGroup()
                                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                                            .addGap(2, 2, 2)
                                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel18)
                                        .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                                            .addComponent(jLabel19)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel21)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel22))
                                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                                            .addComponent(ftCep, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(coUf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(ftFone, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(pnManutencaoLayout.createSequentialGroup()
                                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(ftAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(ftDemissao))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                                        .addComponent(tfLogradouro))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel16)
                                        .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnManutencaoLayout.createSequentialGroup()
                                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                                            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(ftNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(tfNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(ftCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(tfRg, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(ftOrgexp, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel10)))
                                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                                            .addComponent(ftCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(tfNome))
                                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jLabel4)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                                            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rbMasculino)
                                                .addComponent(tfCtps, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel11))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(rbFeminino)
                                                .addComponent(jLabel12)
                                                .addComponent(tfSerie, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                            .addComponent(jLabel24)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel25)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel26)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel27))
                        .addGroup(pnManutencaoLayout.createSequentialGroup()
                            .addComponent(ftCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(coDpto, 0, 174, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(ftSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(pnManutencaoLayout.createSequentialGroup()
                    .addGap(239, 239, 239)
                    .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(60, 60, 60)
                    .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(60, 60, 60)
                    .addComponent(btExcluir)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ftCodigo, jLabel3});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ftNascimento, jLabel23, tfNacionalidade});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ftCpf, jLabel8});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel9, tfRg});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ftOrgexp, jLabel10});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel11, tfCtps});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ftFone, jLabel12, jLabel16, jLabel22, tfNumero, tfSerie});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ftAdmissao, ftDemissao, jLabel13, jLabel14, jLabel18, tfBairro, tfComplemento});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ftCep, jLabel19});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {coUf, jLabel21});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel20, tfCidade});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ftCelular, jLabel24});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {coDpto, jLabel25});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ftSalario, jLabel26, jLabel27, tfFuncao});

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btAlterar, btExcluir});

    pnManutencaoLayout.setVerticalGroup(
        pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(pnManutencaoLayout.createSequentialGroup()
            .addContainerGap()
            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addComponent(jLabel2))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnManutencaoLayout.createSequentialGroup()
                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ftCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(rbMasculino)
                        .addComponent(rbFeminino))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9)
                        .addComponent(jLabel10)
                        .addComponent(jLabel11)
                        .addComponent(jLabel12)
                        .addComponent(jLabel23))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ftNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ftCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfRg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfCtps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfSerie, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ftOrgexp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(jLabel14)
                        .addComponent(jLabel15)
                        .addComponent(jLabel16))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ftAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ftDemissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel17)
                        .addComponent(jLabel18)
                        .addComponent(jLabel19)
                        .addComponent(jLabel20)
                        .addComponent(jLabel21)
                        .addComponent(jLabel22))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ftCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(coUf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ftFone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel24)
                .addComponent(jLabel25)
                .addComponent(jLabel26)
                .addComponent(jLabel27))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(ftCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(coDpto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(tfFuncao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(ftSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
            .addGroup(pnManutencaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btExcluir))
            .addContainerGap())
    );

    pnManutencaoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btAlterar, btExcluir});

    tpAbas.addTab("Manutenção", pnManutencao);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(tpAbas, javax.swing.GroupLayout.DEFAULT_SIZE, 952, Short.MAX_VALUE)
            .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(tpAbas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 470, Short.MAX_VALUE)
    );

    tpAbas.getAccessibleContext().setAccessibleName("");

    pack();
    }// </editor-fold>//GEN-END:initComponents
    private static final Logger LOG = Logger.getLogger(APFuncionario1.class.getName());// </editor-fold>     

    
    private void btAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlterarActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == btAlterar){
            alterar();
        }
    }//GEN-LAST:event_btAlterarActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        // TODO add your handling code here:
        if (evt.getSource() == btSalvar) {
            incluir();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void rbFemininoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbFemininoActionPerformed
        // TODO add your handling code here:
        if (rbFeminino.isSelected()) {
            sexo = "FEMININO";
            
        }
    }//GEN-LAST:event_rbFemininoActionPerformed

    private void rbMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbMasculinoActionPerformed
        // TODO add your handling code here:
        if (rbMasculino.isSelected()) {
            sexo = "MASCULINO";
        }
    }//GEN-LAST:event_rbMasculinoActionPerformed

    private void tpAbasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tpAbasStateChanged
        // TODO add your handling code here:
        if(tpAbas.getSelectedIndex() != 0)return;
        for(int i = 0; i < pnManutencao.getComponentCount(); i++){
            if(pnManutencao.getComponent(i) instanceof JTextComponent)
                ((JTextComponent)pnManutencao.getComponent(i)).setText("");
            if(pnManutencao.getComponent(i) instanceof JComboBox)
                ((JComboBox)pnManutencao.getComponent(i)).setSelectedIndex(0);
        }
    }//GEN-LAST:event_tpAbasStateChanged

    private void btExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btExcluirActionPerformed
        // TODO add your handling code here:
        if(evt.getSource() == btExcluir){
            int opcao = showOptionDialog(this, "Tem certeza que deseja excluir esse funcionário?", "Confirme", 0,
                    QUESTION_MESSAGE, null, new String[]{"Sim", "Não"}, "Não");
            if (opcao == -1) {
                return;
            } else if (opcao == 0) {
                excluir();
            } else if (opcao == 1) {
                return;
            }            
        }
    }//GEN-LAST:event_btExcluirActionPerformed
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.JButton btAlterar;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btSalvar;
    private javax.swing.JComboBox coDpto;
    private javax.swing.JComboBox coUf;
    private javax.swing.JFormattedTextField ftAdmissao;
    private javax.swing.JFormattedTextField ftCelular;
    private javax.swing.JFormattedTextField ftCep;
    private javax.swing.JFormattedTextField ftCodigo;
    private javax.swing.JFormattedTextField ftCpf;
    private javax.swing.JFormattedTextField ftDemissao;
    private javax.swing.JFormattedTextField ftFone;
    private javax.swing.JFormattedTextField ftNascimento;
    private javax.swing.JFormattedTextField ftOrgexp;
    private javax.swing.JFormattedTextField ftSalario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel pnManutencao;
    private javax.swing.JRadioButton rbFeminino;
    private javax.swing.JRadioButton rbMasculino;
    private javax.swing.JScrollPane spDados;
    private javax.swing.JTable tbDados;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JTextField tfComplemento;
    private javax.swing.JTextField tfCtps;
    private javax.swing.JTextField tfFuncao;
    private javax.swing.JTextField tfLogradouro;
    private javax.swing.JTextField tfNacionalidade;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfRg;
    private javax.swing.JTextField tfSerie;
    private javax.swing.JTabbedPane tpAbas;
    // End of variables declaration//GEN-END:variables
}
